print("The Fool: Beginnings, Risks, Spontaneity")
print("The Magician: Manifestation, Resourcefulness, Power")
print("The High Priestess: Intuition, Secrets, Unconscious")
print("The Empress: Abundance, Mothering, Nature")
print("The Emperor: Authority, Fathering, Control")
print("The Hierophant: Tradition, Conformity, Spirituality")
print("The Lovers: Love, Harmony, Trust")
print("The Chariot: Determination, Willpower, Victory")
print("Strength: Courage, Inner Strength, Self-Control")
print("The Hermit: Soul-Searching, Solitude, Inner Guidance")
print("Wheel of Fortune: Change, Cycles, Fate")
print("Justice: Fairness, Justice, Balance")
print("The Hanged Man: Surrender, Letting Go, Perspective")
print("Death: Endings, Transformation, Change")
print("Temperance: Balance, Harmony, Moderation")
print("The Devil: Materialism, Egoism, Ignorance")
print("The Tower: Destruction, Upheaval, Revelation")
print("The Star: Hope, Inspiration, Serenity")
print("The Moon: Illusion, Fear, Subconscious")
print("The Sun: Happiness, Vitality, Confidence")
print("Judgement: Rebirth, Renewal, Awakening")
print("The World: Completion, Integration, Accomplishment")
